/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package GradleFirstProject;

public class Library {
    public boolean someLibraryMethod() {
    	System.out.print("Hiiiiiiiii");
        return true;
    }
}
